### ISSUE TITLE
About compatibility with dorado and para '--sig_move_offset parameter'

### ISSUE THREAD

**Issue by Flower9618** [hiruna72/squigualiser#3]
Hi, thank you so much for sharing this tool.

I wonder if .sam result including move table from `dorado` is compatible with this tool, where move table information is gotten by setting `--emit-moves`.

Secondly, I wonder how I should set `--sig_move_offset parameter` parameters when I run this tool. 

Thank you so much.

**Comment by hiruna72** [comment]
Hi @Flower9618,

Yes you can use dorado's  .sam output as mentioned in [here](https://github.com/hiruna72/squigualiser#option-1---using-move-table-generated-by-the-basecaller) in the ReadMe. But I recommend using Buttery-eel or slow5-dorado instead of dorado as plot.py supports only slow5 files at the moment.

About `sig_move_offset`, it is also described [here](https://github.com/hiruna72/squigualiser#note) in the ReadMe. However, I suggest to just leave it with the default value (1).

**Comment by Flower9618** [comment]
Hi @hiruna72 ,

You mean if I would like to plot the signal, I have to use the result from slow-dorado or Buttery-eel. The .sam file from dorado can not be for plotting, right?

Thank you very much.

**Comment by hiruna72** [comment]
Hi @Flower9618,

Yes you can use the dorado .sam output. But the raw signal shoud be in slow5 format. As you may have read, plottiing a read has 3 steps.
1. Run basecaller (can be dorado, slow5-dorado, buttery-eel, or guppy)
2. Reform the move table
3. Plot the read (raw signal should be in slow5 format)

**Comment by Flower9618** [comment]
Hi @hiruna72 ,
Is there any way to transfer .pod5 to .slow5?

**Comment by hiruna72** [comment]
Yes you can use [slow5tools f2s](https://github.com/hasindu2008/slow5tools)

**Comment by Flower9618** [comment]
Thank you so much. I also find this tool just now. So, I can use the .sam from dorado. At the same time, I transfer .fast5 to .slow5. Then, I can plot the signal using these two files.

**Comment by hiruna72** [comment]
Hi @Flower9618,

Please feel free to reopen this issue if there is more to discuss.

**Comment by UmairK291095** [comment]
are there any other tool which can convert pod5 to slow5?

**Comment by Psy-Fer** [comment]
Hello,

Yes there is. I wrote blue-crab to do just that.

https://github.com/Psy-Fer/blue-crab

James

**Comment by UmairK291095** [comment]
Thank you
