### ISSUE TITLE
Reform parameters (-k & -m) for RNA002 libraries?

### ISSUE THREAD

**Issue by lkwhite** [hiruna72/squigualiser#48]
Hi again, still familiarizing myself with the tool and have another question. For RNA libraries, you have [this nice walkthrough](https://github.com/hiruna72/squigualiser/blob/main/docs/RNA_visualisation.md). I see you've got some preset profiles for running `reform.py` on DNA libraries, but not for RNA. What parameters did you use for this RNA data set? I'm guessing from the [pore model documentation](https://github.com/hiruna72/squigualiser/blob/main/docs/pore_model.md) that your offset -m is 1, but I'm less clear on where the kmer length -k in these profiles is derived from.

I also see you have a table with -k 5 and -m -3 [here](https://github.com/hiruna72/squigualiser/blob/main/docs/base_shift_of_reverse_mapped_reads.md) (at least for forward mapped reads, which is all I have). Anyway, just hoping you might have some guidance before I start testing a bunch of options.

**Comment by hiruna72** [comment]
Hello @lkwhite,

1. Only reads mapped to a transcriptome are supported for RNA. Hence, no reverse mapped reads https://github.com/hiruna72/squigualiser#plot-conventions.
2. As listed [here](https://github.com/hiruna72/squigualiser/blob/main/docs/profiles.md#profiles) if you use `rna_r9.4.1_70bps_fast_prom` model from guppy you can set -k 1 and -m 0. Otherwise you have to use [calculate offsets](https://github.com/hiruna72/squigualiser/blob/main/docs/calculate_offsets.md) program to derive the k and m values. **What is the basecalling model you are planning to use?**
3. Sorry I will document this better. However the idea is if you get the -k and -m values at reform stage correct, then you don't have to worry about base shift parameter at the plotting stage (for input coming through reform).
4. You can use [this pipeline script](https://github.com/hiruna72/squigualiser/tree/main/test/data/raw/pipelines/pipeline_0/rna_r9.4.1_70bps) and the blow5 file to get started. Please note that this script is a guide only and might not work in the first go. You have to execute the script sitting inside the script's directory. The details of different variables and functions of the script are listed [here](https://github.com/hiruna72/squigualiser/blob/main/docs/pipeline_basic.md)

Thanks for bringing up these questions. I will improve the documentation. Let me know how it goes.

**Comment by lkwhite** [comment]
Hi @hiruna72,
These are reads base called with `rna_r9.4.1_70bps_hac_prom`, so sounds like we might need to calculate our own offsets. Thanks for the quick response and pointers!

**Comment by hiruna72** [comment]
Hi @lkwhite,

When I tried the script myself I encountered a bug which I fixed in the newest version.
There is a new pip version released today https://pypi.org/project/squigualiser/0.5.0/.
Or download the linux or macos version from the [release](https://github.com/hiruna72/squigualiser/releases/tag/v0.5.0)


I updated the profiles table to include `rna_r9.4.1_70bps_hac_prom` and it has -k1 and -m0 values.

**Comment by hiruna72** [comment]
Hi @lkwhite,

Thank you for using squigualiser.
Hope your issues are resolved.
Please feel free to reopen the issue should you need further help.
